
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicServices", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://www.uid-wse-a.admin.ch/V5.0/PublicServices.svc?wsdl")
public class PublicServices
    extends Service
{

    private final static URL PUBLICSERVICES_WSDL_LOCATION;
    private final static WebServiceException PUBLICSERVICES_EXCEPTION;
    private final static QName PUBLICSERVICES_QNAME = new QName("http://tempuri.org/", "PublicServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.uid-wse-a.admin.ch/V5.0/PublicServices.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICSERVICES_WSDL_LOCATION = url;
        PUBLICSERVICES_EXCEPTION = e;
    }

    public PublicServices() {
        super(__getWsdlLocation(), PUBLICSERVICES_QNAME);
    }

    public PublicServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICSERVICES_QNAME, features);
    }

    public PublicServices(URL wsdlLocation) {
        super(wsdlLocation, PUBLICSERVICES_QNAME);
    }

    public PublicServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICSERVICES_QNAME, features);
    }

    public PublicServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPublicServices
     */
    @WebEndpoint(name = "BasicHttpBinding_IPublicServices")
    public IPublicServices getBasicHttpBindingIPublicServices() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPublicServices"), IPublicServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPublicServices
     */
    @WebEndpoint(name = "BasicHttpBinding_IPublicServices")
    public IPublicServices getBasicHttpBindingIPublicServices(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPublicServices"), IPublicServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICSERVICES_EXCEPTION!= null) {
            throw PUBLICSERVICES_EXCEPTION;
        }
        return PUBLICSERVICES_WSDL_LOCATION;
    }

}
